name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  gh-pages:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Nix downloads
        uses: actions/cache@v3
        with:
          path: /nix/store
          key: nix-store-${{ hashFiles('flake.nix flake.lock shell.nix') }}

      - name: Cache Nodejs downloads
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package.json package-lock.json') }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Cache Nix builds
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Install Nix package dependencies
        run: |
          nix-channel --update
          nix-shell --run true

      - name: Install Node module dependencies
        run: |
          nix-shell --run 'npm ci'

      - name: Generate static site pages
        run: |
          nix-shell --pure --run 'make public'

      - name: Inject CNAME
        if: ${{ github.repository == 'alerque/polytype' }}
        run: |
          nix-shell --pure --run 'make public/CNAME'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
