name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  gh-pages:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Cache Nix dependencies
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Install project dependencies
        run: |
          nix-channel --update
          nix-shell --run true

      - name: Generate static site pages
        run: |
          nix-shell --pure --run 'make public'

      - name: Inject CNAME
        if: ${{ github.repository == 'alerque/polytype' }}
        run: |
          nix-shell --pure --run 'make public/CNAME'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
